server:
  port: 8082

spring:
  application:
    name: job-service

  datasource:
    url: jdbc:mysql://localhost:3307/smart_job_portal_job_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: QwErTyUiOpGhJfDs7458LmN5JbVg74XcDZo
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connection-timeout: 5000
        read-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info