server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/
  server:
    wait-time-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 5000
    registry-sync-retry-wait-ms: 0

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
